spring:
  datasource:
    username: root
    url: jdbc:mysql://3.38.146.80:3306/cosmost
#    url: jdbc:mysql://localhost:3306/cosmost_db
    #    url: jdbc:mysql://localhost:3308/cosmost_db
    password: '1234'